services:
  postgres-teams:
    image: postgres:16-alpine
    ports:
      - 1501:5432
    volumes:
      - uservice_teams_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  uservice_teams_postgres:
