// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDeleteTeamService is an autogenerated mock type for the DeleteTeamService type
type MockDeleteTeamService struct {
	mock.Mock
}

type MockDeleteTeamService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteTeamService) EXPECT() *MockDeleteTeamService_Expecter {
	return &MockDeleteTeamService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, teamID
func (_m *MockDeleteTeamService) Exec(ctx context.Context, teamID string) error {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeleteTeamService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockDeleteTeamService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *MockDeleteTeamService_Expecter) Exec(ctx interface{}, teamID interface{}) *MockDeleteTeamService_Exec_Call {
	return &MockDeleteTeamService_Exec_Call{Call: _e.mock.On("Exec", ctx, teamID)}
}

func (_c *MockDeleteTeamService_Exec_Call) Run(run func(ctx context.Context, teamID string)) *MockDeleteTeamService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDeleteTeamService_Exec_Call) Return(_a0 error) *MockDeleteTeamService_Exec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeleteTeamService_Exec_Call) RunAndReturn(run func(context.Context, string) error) *MockDeleteTeamService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleteTeamService creates a new instance of MockDeleteTeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteTeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteTeamService {
	mock := &MockDeleteTeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
