// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-teams/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockSetTeamOwnerService is an autogenerated mock type for the SetTeamOwnerService type
type MockSetTeamOwnerService struct {
	mock.Mock
}

type MockSetTeamOwnerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSetTeamOwnerService) EXPECT() *MockSetTeamOwnerService_Expecter {
	return &MockSetTeamOwnerService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, in
func (_m *MockSetTeamOwnerService) Exec(ctx context.Context, in *models.SetTeamOwnerRequest) (*models.Team, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.SetTeamOwnerRequest) (*models.Team, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.SetTeamOwnerRequest) *models.Team); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.SetTeamOwnerRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSetTeamOwnerService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockSetTeamOwnerService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - in *models.SetTeamOwnerRequest
func (_e *MockSetTeamOwnerService_Expecter) Exec(ctx interface{}, in interface{}) *MockSetTeamOwnerService_Exec_Call {
	return &MockSetTeamOwnerService_Exec_Call{Call: _e.mock.On("Exec", ctx, in)}
}

func (_c *MockSetTeamOwnerService_Exec_Call) Run(run func(ctx context.Context, in *models.SetTeamOwnerRequest)) *MockSetTeamOwnerService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.SetTeamOwnerRequest))
	})
	return _c
}

func (_c *MockSetTeamOwnerService_Exec_Call) Return(_a0 *models.Team, _a1 error) *MockSetTeamOwnerService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSetTeamOwnerService_Exec_Call) RunAndReturn(run func(context.Context, *models.SetTeamOwnerRequest) (*models.Team, error)) *MockSetTeamOwnerService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSetTeamOwnerService creates a new instance of MockSetTeamOwnerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSetTeamOwnerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSetTeamOwnerService {
	mock := &MockSetTeamOwnerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
