// Code generated by mockery v2.46.0. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-teams/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockListTeamMembersService is an autogenerated mock type for the ListTeamMembersService type
type MockListTeamMembersService struct {
	mock.Mock
}

type MockListTeamMembersService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListTeamMembersService) EXPECT() *MockListTeamMembersService_Expecter {
	return &MockListTeamMembersService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, in
func (_m *MockListTeamMembersService) Exec(ctx context.Context, in *models.ListTeamMembersRequest) ([]*models.TeamMember, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*models.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.ListTeamMembersRequest) ([]*models.TeamMember, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.ListTeamMembersRequest) []*models.TeamMember); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.ListTeamMembersRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListTeamMembersService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockListTeamMembersService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - in *models.ListTeamMembersRequest
func (_e *MockListTeamMembersService_Expecter) Exec(ctx interface{}, in interface{}) *MockListTeamMembersService_Exec_Call {
	return &MockListTeamMembersService_Exec_Call{Call: _e.mock.On("Exec", ctx, in)}
}

func (_c *MockListTeamMembersService_Exec_Call) Run(run func(ctx context.Context, in *models.ListTeamMembersRequest)) *MockListTeamMembersService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.ListTeamMembersRequest))
	})
	return _c
}

func (_c *MockListTeamMembersService_Exec_Call) Return(_a0 []*models.TeamMember, _a1 error) *MockListTeamMembersService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListTeamMembersService_Exec_Call) RunAndReturn(run func(context.Context, *models.ListTeamMembersRequest) ([]*models.TeamMember, error)) *MockListTeamMembersService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListTeamMembersService creates a new instance of MockListTeamMembersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListTeamMembersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListTeamMembersService {
	mock := &MockListTeamMembersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
