// Code generated by mockery v2.46.0. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-teams/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockCreateTeamMemberService is an autogenerated mock type for the CreateTeamMemberService type
type MockCreateTeamMemberService struct {
	mock.Mock
}

type MockCreateTeamMemberService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateTeamMemberService) EXPECT() *MockCreateTeamMemberService_Expecter {
	return &MockCreateTeamMemberService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, in
func (_m *MockCreateTeamMemberService) Exec(ctx context.Context, in *models.CreateTeamMemberRequest) (*models.TeamMember, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *models.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateTeamMemberRequest) (*models.TeamMember, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateTeamMemberRequest) *models.TeamMember); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.CreateTeamMemberRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateTeamMemberService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockCreateTeamMemberService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - in *models.CreateTeamMemberRequest
func (_e *MockCreateTeamMemberService_Expecter) Exec(ctx interface{}, in interface{}) *MockCreateTeamMemberService_Exec_Call {
	return &MockCreateTeamMemberService_Exec_Call{Call: _e.mock.On("Exec", ctx, in)}
}

func (_c *MockCreateTeamMemberService_Exec_Call) Run(run func(ctx context.Context, in *models.CreateTeamMemberRequest)) *MockCreateTeamMemberService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.CreateTeamMemberRequest))
	})
	return _c
}

func (_c *MockCreateTeamMemberService_Exec_Call) Return(_a0 *models.TeamMember, _a1 error) *MockCreateTeamMemberService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateTeamMemberService_Exec_Call) RunAndReturn(run func(context.Context, *models.CreateTeamMemberRequest) (*models.TeamMember, error)) *MockCreateTeamMemberService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateTeamMemberService creates a new instance of MockCreateTeamMemberService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateTeamMemberService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateTeamMemberService {
	mock := &MockCreateTeamMemberService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
