// Code generated by mockery v2.46.0. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-teams/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockJoinTeamWithInvitationService is an autogenerated mock type for the JoinTeamWithInvitationService type
type MockJoinTeamWithInvitationService struct {
	mock.Mock
}

type MockJoinTeamWithInvitationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJoinTeamWithInvitationService) EXPECT() *MockJoinTeamWithInvitationService_Expecter {
	return &MockJoinTeamWithInvitationService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, in
func (_m *MockJoinTeamWithInvitationService) Exec(ctx context.Context, in *models.JoinTeamWithInvitationRequest) (*models.JoinTeamWithInvitationResponse, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *models.JoinTeamWithInvitationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.JoinTeamWithInvitationRequest) (*models.JoinTeamWithInvitationResponse, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.JoinTeamWithInvitationRequest) *models.JoinTeamWithInvitationResponse); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.JoinTeamWithInvitationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.JoinTeamWithInvitationRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJoinTeamWithInvitationService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJoinTeamWithInvitationService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - in *models.JoinTeamWithInvitationRequest
func (_e *MockJoinTeamWithInvitationService_Expecter) Exec(ctx interface{}, in interface{}) *MockJoinTeamWithInvitationService_Exec_Call {
	return &MockJoinTeamWithInvitationService_Exec_Call{Call: _e.mock.On("Exec", ctx, in)}
}

func (_c *MockJoinTeamWithInvitationService_Exec_Call) Run(run func(ctx context.Context, in *models.JoinTeamWithInvitationRequest)) *MockJoinTeamWithInvitationService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.JoinTeamWithInvitationRequest))
	})
	return _c
}

func (_c *MockJoinTeamWithInvitationService_Exec_Call) Return(_a0 *models.JoinTeamWithInvitationResponse, _a1 error) *MockJoinTeamWithInvitationService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJoinTeamWithInvitationService_Exec_Call) RunAndReturn(run func(context.Context, *models.JoinTeamWithInvitationRequest) (*models.JoinTeamWithInvitationResponse, error)) *MockJoinTeamWithInvitationService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJoinTeamWithInvitationService creates a new instance of MockJoinTeamWithInvitationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJoinTeamWithInvitationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJoinTeamWithInvitationService {
	mock := &MockJoinTeamWithInvitationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
