// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-teams/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockGetTeamService is an autogenerated mock type for the GetTeamService type
type MockGetTeamService struct {
	mock.Mock
}

type MockGetTeamService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetTeamService) EXPECT() *MockGetTeamService_Expecter {
	return &MockGetTeamService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, in
func (_m *MockGetTeamService) Exec(ctx context.Context, in *models.GetTeamRequest) (*models.Team, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GetTeamRequest) (*models.Team, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.GetTeamRequest) *models.Team); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.GetTeamRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetTeamService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGetTeamService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - in *models.GetTeamRequest
func (_e *MockGetTeamService_Expecter) Exec(ctx interface{}, in interface{}) *MockGetTeamService_Exec_Call {
	return &MockGetTeamService_Exec_Call{Call: _e.mock.On("Exec", ctx, in)}
}

func (_c *MockGetTeamService_Exec_Call) Run(run func(ctx context.Context, in *models.GetTeamRequest)) *MockGetTeamService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.GetTeamRequest))
	})
	return _c
}

func (_c *MockGetTeamService_Exec_Call) Return(_a0 *models.Team, _a1 error) *MockGetTeamService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetTeamService_Exec_Call) RunAndReturn(run func(context.Context, *models.GetTeamRequest) (*models.Team, error)) *MockGetTeamService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetTeamService creates a new instance of MockGetTeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetTeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetTeamService {
	mock := &MockGetTeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
