// Code generated by mockery v2.46.0. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-teams/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockListUserTeamsService is an autogenerated mock type for the ListUserTeamsService type
type MockListUserTeamsService struct {
	mock.Mock
}

type MockListUserTeamsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListUserTeamsService) EXPECT() *MockListUserTeamsService_Expecter {
	return &MockListUserTeamsService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, in
func (_m *MockListUserTeamsService) Exec(ctx context.Context, in *models.ListUserTeamsRequest) ([]*models.Team, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.ListUserTeamsRequest) ([]*models.Team, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.ListUserTeamsRequest) []*models.Team); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.ListUserTeamsRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListUserTeamsService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockListUserTeamsService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - in *models.ListUserTeamsRequest
func (_e *MockListUserTeamsService_Expecter) Exec(ctx interface{}, in interface{}) *MockListUserTeamsService_Exec_Call {
	return &MockListUserTeamsService_Exec_Call{Call: _e.mock.On("Exec", ctx, in)}
}

func (_c *MockListUserTeamsService_Exec_Call) Run(run func(ctx context.Context, in *models.ListUserTeamsRequest)) *MockListUserTeamsService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.ListUserTeamsRequest))
	})
	return _c
}

func (_c *MockListUserTeamsService_Exec_Call) Return(_a0 []*models.Team, _a1 error) *MockListUserTeamsService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListUserTeamsService_Exec_Call) RunAndReturn(run func(context.Context, *models.ListUserTeamsRequest) ([]*models.Team, error)) *MockListUserTeamsService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListUserTeamsService creates a new instance of MockListUserTeamsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListUserTeamsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListUserTeamsService {
	mock := &MockListUserTeamsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
