// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockDeleteTeamRepository is an autogenerated mock type for the DeleteTeamRepository type
type MockDeleteTeamRepository struct {
	mock.Mock
}

type MockDeleteTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteTeamRepository) EXPECT() *MockDeleteTeamRepository_Expecter {
	return &MockDeleteTeamRepository_Expecter{mock: &_m.Mock}
}

// DeleteTeam provides a mock function with given fields: ctx, team
func (_m *MockDeleteTeamRepository) DeleteTeam(ctx context.Context, team uuid.UUID) error {
	ret := _m.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, team)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeleteTeamRepository_DeleteTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTeam'
type MockDeleteTeamRepository_DeleteTeam_Call struct {
	*mock.Call
}

// DeleteTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - team uuid.UUID
func (_e *MockDeleteTeamRepository_Expecter) DeleteTeam(ctx interface{}, team interface{}) *MockDeleteTeamRepository_DeleteTeam_Call {
	return &MockDeleteTeamRepository_DeleteTeam_Call{Call: _e.mock.On("DeleteTeam", ctx, team)}
}

func (_c *MockDeleteTeamRepository_DeleteTeam_Call) Run(run func(ctx context.Context, team uuid.UUID)) *MockDeleteTeamRepository_DeleteTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeleteTeamRepository_DeleteTeam_Call) Return(_a0 error) *MockDeleteTeamRepository_DeleteTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeleteTeamRepository_DeleteTeam_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockDeleteTeamRepository_DeleteTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleteTeamRepository creates a new instance of MockDeleteTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteTeamRepository {
	mock := &MockDeleteTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
