// Code generated by mockery v2.46.0. DO NOT EDIT.

package daomocks

import (
	context "context"

	dao "github.com/in-rich/uservice-teams/pkg/dao"
	entities "github.com/in-rich/uservice-teams/pkg/entities"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCreateInvitationCodeRepository is an autogenerated mock type for the CreateInvitationCodeRepository type
type MockCreateInvitationCodeRepository struct {
	mock.Mock
}

type MockCreateInvitationCodeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateInvitationCodeRepository) EXPECT() *MockCreateInvitationCodeRepository_Expecter {
	return &MockCreateInvitationCodeRepository_Expecter{mock: &_m.Mock}
}

// CreateInvitationCode provides a mock function with given fields: ctx, id, data
func (_m *MockCreateInvitationCodeRepository) CreateInvitationCode(ctx context.Context, id uuid.UUID, data *dao.CreateInvitationCodeData) (*entities.InvitationCode, error) {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvitationCode")
	}

	var r0 *entities.InvitationCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *dao.CreateInvitationCodeData) (*entities.InvitationCode, error)); ok {
		return rf(ctx, id, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *dao.CreateInvitationCodeData) *entities.InvitationCode); ok {
		r0 = rf(ctx, id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.InvitationCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *dao.CreateInvitationCodeData) error); ok {
		r1 = rf(ctx, id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateInvitationCodeRepository_CreateInvitationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvitationCode'
type MockCreateInvitationCodeRepository_CreateInvitationCode_Call struct {
	*mock.Call
}

// CreateInvitationCode is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - data *dao.CreateInvitationCodeData
func (_e *MockCreateInvitationCodeRepository_Expecter) CreateInvitationCode(ctx interface{}, id interface{}, data interface{}) *MockCreateInvitationCodeRepository_CreateInvitationCode_Call {
	return &MockCreateInvitationCodeRepository_CreateInvitationCode_Call{Call: _e.mock.On("CreateInvitationCode", ctx, id, data)}
}

func (_c *MockCreateInvitationCodeRepository_CreateInvitationCode_Call) Run(run func(ctx context.Context, id uuid.UUID, data *dao.CreateInvitationCodeData)) *MockCreateInvitationCodeRepository_CreateInvitationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*dao.CreateInvitationCodeData))
	})
	return _c
}

func (_c *MockCreateInvitationCodeRepository_CreateInvitationCode_Call) Return(_a0 *entities.InvitationCode, _a1 error) *MockCreateInvitationCodeRepository_CreateInvitationCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateInvitationCodeRepository_CreateInvitationCode_Call) RunAndReturn(run func(context.Context, uuid.UUID, *dao.CreateInvitationCodeData) (*entities.InvitationCode, error)) *MockCreateInvitationCodeRepository_CreateInvitationCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateInvitationCodeRepository creates a new instance of MockCreateInvitationCodeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateInvitationCodeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateInvitationCodeRepository {
	mock := &MockCreateInvitationCodeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
