// Code generated by mockery v2.46.0. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/in-rich/uservice-teams/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockListUserTeamsRepository is an autogenerated mock type for the ListUserTeamsRepository type
type MockListUserTeamsRepository struct {
	mock.Mock
}

type MockListUserTeamsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListUserTeamsRepository) EXPECT() *MockListUserTeamsRepository_Expecter {
	return &MockListUserTeamsRepository_Expecter{mock: &_m.Mock}
}

// ListUserTeams provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockListUserTeamsRepository) ListUserTeams(ctx context.Context, userID string, limit int, offset int) ([]*entities.Team, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListUserTeams")
	}

	var r0 []*entities.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*entities.Team, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*entities.Team); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListUserTeamsRepository_ListUserTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserTeams'
type MockListUserTeamsRepository_ListUserTeams_Call struct {
	*mock.Call
}

// ListUserTeams is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *MockListUserTeamsRepository_Expecter) ListUserTeams(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockListUserTeamsRepository_ListUserTeams_Call {
	return &MockListUserTeamsRepository_ListUserTeams_Call{Call: _e.mock.On("ListUserTeams", ctx, userID, limit, offset)}
}

func (_c *MockListUserTeamsRepository_ListUserTeams_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *MockListUserTeamsRepository_ListUserTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockListUserTeamsRepository_ListUserTeams_Call) Return(_a0 []*entities.Team, _a1 error) *MockListUserTeamsRepository_ListUserTeams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListUserTeamsRepository_ListUserTeams_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*entities.Team, error)) *MockListUserTeamsRepository_ListUserTeams_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListUserTeamsRepository creates a new instance of MockListUserTeamsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListUserTeamsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListUserTeamsRepository {
	mock := &MockListUserTeamsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
