// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/in-rich/uservice-teams/pkg/entities"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockListTeamMembersRepository is an autogenerated mock type for the ListTeamMembersRepository type
type MockListTeamMembersRepository struct {
	mock.Mock
}

type MockListTeamMembersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListTeamMembersRepository) EXPECT() *MockListTeamMembersRepository_Expecter {
	return &MockListTeamMembersRepository_Expecter{mock: &_m.Mock}
}

// ListTeamMembers provides a mock function with given fields: ctx, teamID, limit, offset
func (_m *MockListTeamMembersRepository) ListTeamMembers(ctx context.Context, teamID uuid.UUID, limit int, offset int) ([]*entities.TeamMember, error) {
	ret := _m.Called(ctx, teamID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListTeamMembers")
	}

	var r0 []*entities.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entities.TeamMember, error)); ok {
		return rf(ctx, teamID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entities.TeamMember); ok {
		r0 = rf(ctx, teamID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, teamID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListTeamMembersRepository_ListTeamMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTeamMembers'
type MockListTeamMembersRepository_ListTeamMembers_Call struct {
	*mock.Call
}

// ListTeamMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockListTeamMembersRepository_Expecter) ListTeamMembers(ctx interface{}, teamID interface{}, limit interface{}, offset interface{}) *MockListTeamMembersRepository_ListTeamMembers_Call {
	return &MockListTeamMembersRepository_ListTeamMembers_Call{Call: _e.mock.On("ListTeamMembers", ctx, teamID, limit, offset)}
}

func (_c *MockListTeamMembersRepository_ListTeamMembers_Call) Run(run func(ctx context.Context, teamID uuid.UUID, limit int, offset int)) *MockListTeamMembersRepository_ListTeamMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockListTeamMembersRepository_ListTeamMembers_Call) Return(_a0 []*entities.TeamMember, _a1 error) *MockListTeamMembersRepository_ListTeamMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListTeamMembersRepository_ListTeamMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*entities.TeamMember, error)) *MockListTeamMembersRepository_ListTeamMembers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListTeamMembersRepository creates a new instance of MockListTeamMembersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListTeamMembersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListTeamMembersRepository {
	mock := &MockListTeamMembersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
