// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	dao "github.com/in-rich/uservice-teams/pkg/dao"
	entities "github.com/in-rich/uservice-teams/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockCreateTeamRepository is an autogenerated mock type for the CreateTeamRepository type
type MockCreateTeamRepository struct {
	mock.Mock
}

type MockCreateTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateTeamRepository) EXPECT() *MockCreateTeamRepository_Expecter {
	return &MockCreateTeamRepository_Expecter{mock: &_m.Mock}
}

// CreateTeam provides a mock function with given fields: ctx, data
func (_m *MockCreateTeamRepository) CreateTeam(ctx context.Context, data *dao.CreateTeamData) (*entities.Team, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 *entities.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dao.CreateTeamData) (*entities.Team, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dao.CreateTeamData) *entities.Team); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dao.CreateTeamData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateTeamRepository_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockCreateTeamRepository_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - data *dao.CreateTeamData
func (_e *MockCreateTeamRepository_Expecter) CreateTeam(ctx interface{}, data interface{}) *MockCreateTeamRepository_CreateTeam_Call {
	return &MockCreateTeamRepository_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, data)}
}

func (_c *MockCreateTeamRepository_CreateTeam_Call) Run(run func(ctx context.Context, data *dao.CreateTeamData)) *MockCreateTeamRepository_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dao.CreateTeamData))
	})
	return _c
}

func (_c *MockCreateTeamRepository_CreateTeam_Call) Return(_a0 *entities.Team, _a1 error) *MockCreateTeamRepository_CreateTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateTeamRepository_CreateTeam_Call) RunAndReturn(run func(context.Context, *dao.CreateTeamData) (*entities.Team, error)) *MockCreateTeamRepository_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateTeamRepository creates a new instance of MockCreateTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateTeamRepository {
	mock := &MockCreateTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
