name: clean

on: [ delete ]

jobs:
  delete-docker:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      IMAGE_NAME: ${{ github.event.repository.name }}/${{ github.event.ref }}
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@abd519f0d4139a1c79766c4859d3a301fb3a8daa
        with:
          package-name: ${{ env.IMAGE_NAME }}
          package-type: 'container'
          delete-only-pre-release-versions: false
          delete-only-untagged-versions: false
          min-versions-to-keep: 0
