name: clean
on: [ delete ]

jobs:
  delete-docker:
    if: github.event.ref_type == 'branch'
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: in-rich/workflows/.github/workflows/clean-container.yaml@master
    with:
      repository_name: ${{ github.event.repository.name }}
      ref: ${{ github.event.ref }}
      actor: ${{ github.actor }}
